# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(845, 674)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.select_box = QtWidgets.QComboBox(self.page)
        self.select_box.setStyleSheet("font: 18pt \"黑体\";")
        self.select_box.setObjectName("select_box")
        self.select_box.addItem("")
        self.select_box.addItem("")
        self.select_box.addItem("")
        self.select_box.addItem("")
        self.select_box.addItem("")
        self.select_box.addItem("")
        self.select_box.addItem("")
        self.gridLayout_2.addWidget(self.select_box, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setStyleSheet("font: 9pt \"黑体\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        self.label.setStyleSheet("font: 18pt \"黑体\";")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.A_button = QtWidgets.QPushButton(self.page_2)
        self.A_button.setStyleSheet("QPushButton {\n"
"font: 10pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}")
        self.A_button.setObjectName("A_button")
        self.horizontalLayout.addWidget(self.A_button)
        self.B_button = QtWidgets.QPushButton(self.page_2)
        self.B_button.setStyleSheet("QPushButton {\n"
"font: 10pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}")
        self.B_button.setObjectName("B_button")
        self.horizontalLayout.addWidget(self.B_button)
        self.C_button = QtWidgets.QPushButton(self.page_2)
        self.C_button.setStyleSheet("QPushButton {\n"
"font: 10pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}")
        self.C_button.setObjectName("C_button")
        self.horizontalLayout.addWidget(self.C_button)
        self.D_button = QtWidgets.QPushButton(self.page_2)
        self.D_button.setStyleSheet("QPushButton {\n"
"font: 10pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}")
        self.D_button.setObjectName("D_button")
        self.horizontalLayout.addWidget(self.D_button)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.back_button = QtWidgets.QPushButton(self.page_2)
        self.back_button.setStyleSheet("QPushButton {\n"
"font: 10pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}")
        self.back_button.setObjectName("back_button")
        self.horizontalLayout_2.addWidget(self.back_button)
        self.random_button = QtWidgets.QPushButton(self.page_2)
        self.random_button.setStyleSheet("QPushButton {\n"
"font: 10pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}")
        self.random_button.setObjectName("random_button")
        self.horizontalLayout_2.addWidget(self.random_button)
        self.next_button = QtWidgets.QPushButton(self.page_2)
        self.next_button.setStyleSheet("QPushButton {\n"
"font: 10pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}")
        self.next_button.setFlat(False)
        self.next_button.setObjectName("next_button")
        self.horizontalLayout_2.addWidget(self.next_button)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.page_2)
        self.textEdit.setEnabled(True)
        self.textEdit.setStyleSheet("font: 18pt \"黑体\";")
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.page_2)
        self.pushButton.setStyleSheet("QPushButton {\n"
"font: 10pt \"黑体\";\n"
"border-radius:6px;\n"
"color: white;\n"
"padding: 5px 32px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"margin: 4px 2px;\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid #008cba;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008cba;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #06AD56;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_3.addWidget(self.stackedWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        self.select_box.currentIndexChanged['int'].connect(Form.select_question)
        self.next_button.clicked.connect(Form.next_question)
        self.random_button.clicked.connect(Form.random_question)
        self.A_button.clicked.connect(Form.choice_A)
        self.B_button.clicked.connect(Form.choice_B)
        self.C_button.clicked.connect(Form.choice_C)
        self.D_button.clicked.connect(Form.choice_D)
        self.back_button.clicked.connect(Form.back_question)
        self.pushButton.clicked.connect(Form.go_page0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "近代史刷题"))
        self.select_box.setItemText(0, _translate("Form", "选择一套题："))
        self.select_box.setItemText(1, _translate("Form", "1.61道"))
        self.select_box.setItemText(2, _translate("Form", "2.80道"))
        self.select_box.setItemText(3, _translate("Form", "3.20道"))
        self.select_box.setItemText(4, _translate("Form", "4.25道"))
        self.select_box.setItemText(5, _translate("Form", "5.36道"))
        self.select_box.setItemText(6, _translate("Form", "6.67道"))
        self.label_2.setText(_translate("Form", "本程序由杭州电子科技大学数学营(QQ: 797646975)的管理员：20-信管-Obsidian breaker 编写,推荐加群！！！"))
        self.A_button.setText(_translate("Form", "A"))
        self.B_button.setText(_translate("Form", "B"))
        self.C_button.setText(_translate("Form", "C"))
        self.D_button.setText(_translate("Form", "D"))
        self.back_button.setText(_translate("Form", "上一道"))
        self.random_button.setText(_translate("Form", "随机一道"))
        self.next_button.setText(_translate("Form", "下一道"))
        self.pushButton.setText(_translate("Form", "返回"))
